### ISSUE TITLE
请问使用pycharm远程连接服务器配置SAM，应该如何使用您的webUI？

### ISSUE THREAD

**Issue by Kazma11** [varhuman/SAM-webui#2]
/我正在使用pycharm远程连接linux服务器，在服务器上配置SAM请问我应该如何使用您的webUI？
/
/

**Comment by creeponsky** [comment]
这其实涉及到的是你如何访问服务器某个端口程序的问题
如果你在本地能够正常部署。那其实在服务器也是没问题的，如果不能访问可能是网络防火墙、安全组等问题
